{
  "comments": [
    {
      "key": {
        "uuid": "b77b518b_4cde8de1",
        "filename": "/COMMIT_MSG",
        "patchSetId": 2
      },
      "lineNbr": 11,
      "author": {
        "id": 389
      },
      "writtenOn": "2018-08-28T10:15:58Z",
      "side": 1,
      "message": "That should probably be fixed in a more generic way, by setting the DB connection to something invalid during the provider runs.",
      "range": {
        "startLine": 10,
        "startChar": 62,
        "endLine": 11,
        "endChar": 60
      },
      "revId": "81972397804bf589972a9a42e341d520fd7c7531",
      "serverId": "e9e9afe9-4712-486d-8885-f54b72dd1951",
      "unresolved": true
    }
  ]
}